FROM python:3.10-slim
RUN apt update
RUN apt install unzip curl -y
WORKDIR /app
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY . .
RUN pip install ".[tensorflow]"
ENTRYPOINT [ "deepdanbooru" ]
